version: "3.9"

services:

  postgres-db:

    image: postgres:16

    container_name: postgres-db

    restart: unless-stopped

    environment:
      FLASK_CONFIG: docker
      POSTGRES_DB: employee_db
      POSTGRES_USER: employee_user
      POSTGRES_PASSWORD: employee_password

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U employee_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  employee-app:

    build: .

    container_name: employee-app

    restart: unless-stopped

    depends_on:
      postgres-db:
        condition: service_healthy

    ports:
      - "5000:5000"

    env_file:
      - .env

volumes:

  postgres-data: