name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main

jobs:
  test-build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16

        env:
          POSTGRES_DB: employee_db
          POSTGRES_USER: employee_user
          POSTGRES_PASSWORD: employee_password

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready -U employee_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      SECRET_KEY: test-secret

      DEBUG: True

      DB_HOST: localhost

      DB_PORT: 5432

      DB_NAME: employee_db

      DB_USER: employee_user

      DB_PASSWORD: employee_password

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Initialize database
        run: |
          PGPASSWORD=employee_password psql \
            -h localhost \
            -U employee_user \
            -d employee_db \
            -f database/init.sql

          PGPASSWORD=employee_password psql \
            -h localhost \
            -U employee_user \
            -d employee_db \
            -f database/seed.sql

      - name: Run Tests
        run: pytest

      - name: Run Flake8
        run: flake8 .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t saishrane/employee-portal:latest .